spring:
  datasource:
    url: "jdbc:postgresql://postgres:5432/smartstocks"
    username: "smartuser"
    password: "smartpass"
    driverClassName: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: "false"
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

server:
  port: 8080

